# This file was generated by GoReleaser. DO NOT EDIT.
cask "orl" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "745f6df531e5c93868f8b07633faa738ce0ddfd4587dbf28ca47a0c32c0e1cf6"
      url "https://github.com/OpenRelayInc/orl/releases/download/v#{version}/orl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3c4be4139bfb655f58a218a36be4817176642cc724dd298e51256a4618e999a3"
      url "https://github.com/OpenRelayInc/orl/releases/download/v#{version}/orl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2cc56a58301de1b89f1db20c4472ffb9363b8c70db2bc48b2310801ab0d3f853"
      url "https://github.com/OpenRelayInc/orl/releases/download/v#{version}/orl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c9df3bb6585eab7fed03ec07f47fd0e665b94c28c51f8cdb47a7b1d986b4f2aa"
      url "https://github.com/OpenRelayInc/orl/releases/download/v#{version}/orl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "orl"
  desc "The OpenRelay CLI for GPU VMs, clusters, billing, and provider tools."
  homepage "https://github.com/OpenRelayInc/orl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orl"
  manpage "manpages/orl.1"
  bash_completion "completions/orl.bash"
  fish_completion "completions/orl.fish"
  zsh_completion "completions/orl.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/orl"]
    end
  end

  # No zap stanza required
end
