# This file was generated by GoReleaser. DO NOT EDIT.
cask "orl" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "67a111763d507482cf69edf21ca160fb0ff5be4eec1378ad92b9c7a741d00aeb"
      url "https://github.com/OpenRelayInc/orl/releases/download/v#{version}/orl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "194633822b37f9521d60f4e35fafe1e956ee2b149bb7d356f72ca3ce64c0f834"
      url "https://github.com/OpenRelayInc/orl/releases/download/v#{version}/orl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1efc8a6351b6b2e4b238aa1247ba2499e51ec30e71c4968cfdbad955fc8a20c8"
      url "https://github.com/OpenRelayInc/orl/releases/download/v#{version}/orl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5e93cce6b3aacf9d3b9f46d597a922cccd7f32f1a18de1a2caed1c8c5178d0ed"
      url "https://github.com/OpenRelayInc/orl/releases/download/v#{version}/orl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "orl"
  desc "The OpenRelay CLI for GPU VMs, clusters, billing, and provider tools."
  homepage "https://github.com/OpenRelayInc/orl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orl"
  manpage "manpages/orl.1"
  bash_completion "completions/orl.bash"
  fish_completion "completions/orl.fish"
  zsh_completion "completions/orl.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/orl"]
    end
  end

  # No zap stanza required

end
