# This file was generated by GoReleaser. DO NOT EDIT.
cask "orl" do
  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "dd2e5dcce09562b093087192c644b474ad7952089b299ba02d216b424fd419ac"
      url "https://github.com/OpenRelayInc/orl/releases/download/v#{version}/orl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a1a3ee247d351fb1274422baa96e7514e54d02b9917a7d01f47dda09c1c1c085"
      url "https://github.com/OpenRelayInc/orl/releases/download/v#{version}/orl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a4cd39892f85cb9306f16333b7268ce46b26b66ed2c58d68fb18c1d73b4e5f2b"
      url "https://github.com/OpenRelayInc/orl/releases/download/v#{version}/orl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "66ac89edf782550c06dbd1602b8b95558b009025cc240cd920c0226b1eb4d1a7"
      url "https://github.com/OpenRelayInc/orl/releases/download/v#{version}/orl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "orl"
  desc "The OpenRelay CLI for GPU VMs, pods, billing, and provider tools."
  homepage "https://github.com/OpenRelayInc/orl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orl"
  manpage "manpages/orl.1"
  bash_completion "completions/orl.bash"
  fish_completion "completions/orl.fish"
  zsh_completion "completions/orl.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/orl"]
    end
  end

  # No zap stanza required
end
